name: poincare
channels:
  - conda-forge
dependencies:
  - typing_extensions
  - pre-commit
  - pytest
  - tox-conda
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pip
  - pip:
    - symbolite
    - pytest-readme
