name: poincare
channels:
  - conda-forge
dependencies:
  - typing_extensions
  - pre-commit
  - pytest
  - tox-conda
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pint
  - pint-pandas
  - tabulate
  - pip
  - pip:
    - symbolite
